<a href="https://colab.research.google.com/github/Muntasir90629/ML-Algorithm-Python/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(10,2,-2)

array([10,  8,  6,  4])

In [ ]:
np.arange(10,2,-1)

array([10,  9,  8,  7,  6,  5,  4,  3])

In [ ]:
np.linspace(0,15,11)

array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5, 15. ])

In [ ]:
np.linspace(2,4,8)

array([2.        , 2.28571429, 2.57142857, 2.85714286, 3.14285714,
       3.42857143, 3.71428571, 4.        ])

In [ ]:
np.logspace(2,4,8)

array([  100.        ,   193.06977289,   372.75937203,   719.685673  ,
        1389.49549437,  2682.69579528,  5179.47467923, 10000.        ])

In [ ]:
np.random.rand(2,2,2)

array([[[0.91882056, 0.25443294],
        [0.30005341, 0.0578309 ]],

       [[0.2332161 , 0.24034828],
        [0.04112765, 0.19146844]]])

In [ ]:
d=np.random.randint(0,10,size=(5,5))

In [ ]:
d


array([[4, 9, 7, 0, 8],
       [0, 4, 3, 9, 2],
       [4, 2, 5, 3, 2],
       [8, 7, 2, 1, 6],
       [4, 0, 3, 1, 7]])

In [ ]:
d[ : , 1]

array([9, 4, 2, 7, 0])

In [ ]:
d[ : , 1:4]

array([[9, 7, 0],
       [4, 3, 9],
       [2, 5, 3],
       [7, 2, 1],
       [0, 3, 1]])

In [ ]:
d[1:4 , 1:4]

array([[4, 3, 9],
       [2, 5, 3],
       [7, 2, 1]])

In [ ]:
a=np.ones((3,3))
b=np.zeros((3,3))

In [ ]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.concatenate([a,b],axis=1)

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [ ]:
np.vstack([a,b])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.hstack([a,b])

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [ ]:
a=np.ones((6,6))

In [ ]:
a

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
b=np.zeros((6,6))

In [ ]:
b

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
d=np.hstack([a,b])

In [ ]:
d

array([[1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.]])

In [ ]:
d1,d2=np.vsplit(d,[3])

In [ ]:
d1

array([[1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.]])

In [ ]:
d2

array([[1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.]])

In [ ]:
d.ndim

2

In [ ]:
d.shape

(6, 12)

In [ ]:
d.size

72

In [ ]:
z=np.array([1,2,3,4,5,6,7,8,])


In [ ]:
z

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
z.reshape(-2,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
z=np.random.randint(0,99,size=(10,10))

In [ ]:
z


array([[62, 27, 49, 64, 24, 45, 50, 55, 79, 60],
       [15, 12, 12, 16, 42,  9, 10,  6, 98, 73],
       [33, 71, 29, 44, 93,  5, 89, 55, 86, 57],
       [ 7, 96, 81, 63, 92, 59, 95, 35, 66,  7],
       [28, 94, 17, 71, 81,  9, 29, 61, 21, 58],
       [14, 34,  2, 35,  2, 60, 46, 57, 76, 41],
       [38, 42,  4, 21, 63,  7, 91, 90,  6, 94],
       [20, 36, 38, 54, 13, 76,  3, 58, 17, 61],
       [85, 83,  4,  2,  7, 70, 60, 27, 24, 15],
       [35, 98, 98, 29, 43, 73, 25, 38, 45, 58]])

In [ ]:
z.size

100

In [ ]:
z.ndim

2

In [ ]:
z.reshape(5,20)

array([[62, 27, 49, 64, 24, 45, 50, 55, 79, 60, 15, 12, 12, 16, 42,  9,
        10,  6, 98, 73],
       [33, 71, 29, 44, 93,  5, 89, 55, 86, 57,  7, 96, 81, 63, 92, 59,
        95, 35, 66,  7],
       [28, 94, 17, 71, 81,  9, 29, 61, 21, 58, 14, 34,  2, 35,  2, 60,
        46, 57, 76, 41],
       [38, 42,  4, 21, 63,  7, 91, 90,  6, 94, 20, 36, 38, 54, 13, 76,
         3, 58, 17, 61],
       [85, 83,  4,  2,  7, 70, 60, 27, 24, 15, 35, 98, 98, 29, 43, 73,
        25, 38, 45, 58]])

In [ ]:
z.shape

(10, 10)

In [ ]:
y=np.array([1,2,3,4,5,6])

In [ ]:
y[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
y[:,np.newaxis,np.newaxis].shape

(6, 1, 1)

In [ ]:
y.shape

(6,)

In [ ]:
y.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
np.sum(y)

21

In [ ]:
np.max(y)

6

In [ ]:
a=np.random.randint(100,1000,size=(6,6))

In [ ]:
a

array([[440, 807, 631, 783, 821, 974],
       [177, 639, 941, 287, 371, 331],
       [345, 593, 252, 907, 965, 993],
       [109, 568, 860, 113, 370, 430],
       [408, 119, 797, 666, 847, 655],
       [268, 433, 436, 650, 595, 288]])

In [ ]:
np.sum(a,axis=1)

array([4456, 2746, 4055, 2450, 3492, 2670])

In [ ]:
np.sum(a,axis=0)

array([1747, 3159, 3917, 3406, 3969, 3671])

In [ ]:
np.sum(a)

19869